import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { Card, CardHeader, CardDescription, CardContent, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form } from "@/components/ui/form";
// import { zodResolver } from "@hookform/resolvers,zod";
import { ModeToggle } from "@/components/theme-toggle";

import * as z from "zod";
import { FormGroup } from "@/components/FormGroup";
import { useState } from "react";

const formSchema = z.object({
    prompt: z.string(),
});

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "create a prompt...",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {/* <ModeToggle /> */}
        <Card className = "p-8 lg:min-w-[500px]">
          <form className = "flex flex-col gap-4">
            <FormGroup>
              <label className = "font-bold text-xl">Prompt</label>
              <Input type = "text" className = "max-w-xl italic" value = {form.prompt} 
              onChange = {(e) => 
              setForm({
                ...form,
                prompt: e.target.value,
              })}></Input>
            </FormGroup>
            <CardFooter className = "flex justify-end -p-4">
              <Button variant = "default">
                Submit
              </Button>
            </CardFooter>
          </form>
        </Card>
      </main>
    </>
  );
};

export default GeneratePage;

