import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form } from "@/components/ui/form";
import { zodResolver } from "@hookform/resolvers,zod";

import * as z from "zod";

const formSchema = z.object({
    prompt: z.string(),
});

const GeneratePage: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <form className = "gap-6">
            <label className = "font-bold">Prompt</label>
            <Input type = "text" className = "max-w-xl"></Input>
            <Button variant = "default">Submit</Button>
        </form>
      </main>
    </>
  );
};

export default GeneratePage;

